services:
  app:
    build: .
    container_name: my-yt
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./cookies.txt:/app/cookies.txt:ro  # 👈 This line mounts your cookies file
    ports:
      - "3000:3000"
    command: npm start

volumes:
  data:
    driver: local
